AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repositories for Vistora Application'

Resources:
  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: vistora-backend
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only 10 most recent images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: Vistora
        - Key: Environment
          Value: production

  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: vistora-frontend
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only 10 most recent images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: Vistora
        - Key: Environment
          Value: production

Outputs:
  BackendRepositoryUri:
    Description: Backend ECR Repository URI
    Value: !GetAtt BackendRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-BackendRepositoryUri

  FrontendRepositoryUri:
    Description: Frontend ECR Repository URI
    Value: !GetAtt FrontendRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-FrontendRepositoryUri

  BackendRepositoryArn:
    Description: Backend ECR Repository ARN
    Value: !GetAtt BackendRepository.Arn
    Export:
      Name: !Sub ${AWS::StackName}-BackendRepositoryArn

  FrontendRepositoryArn:
    Description: Frontend ECR Repository ARN
    Value: !GetAtt FrontendRepository.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FrontendRepositoryArn
