AWSTemplateFormatVersion: '2010-09-09'
Description: 'Vistora Monitoring Stack - CloudWatch Alarms and SNS'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name prefix

  ECSClusterName:
    Type: String
    Description: ECS Cluster Name

  BackendServiceName:
    Type: String
    Description: Backend Service Name

  FrontendServiceName:
    Type: String
    Description: Frontend Service Name

  ALBTargetGroupArn:
    Type: String
    Description: ALB Target Group ARN

  AlertEmail:
    Type: String
    Description: Email address for alarm notifications
    Default: admin@example.com

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${EnvironmentName}-alerts
      DisplayName: Vistora Alerts
      Subscription:
        - Endpoint: !Ref AlertEmail
          Protocol: email
      Tags:
        - Key: Project
          Value: Vistora

  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-high-error-rate
      AlarmDescription: Alert when error rate exceeds 5% for 5 minutes
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  HighResponseTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-high-response-time
      AlarmDescription: Alert when response time exceeds 2 seconds for 3 minutes
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 2.0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  BackendCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-backend-high-cpu
      AlarmDescription: Alert when backend CPU exceeds 70% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref BackendServiceName
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  FrontendCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-frontend-high-cpu
      AlarmDescription: Alert when frontend CPU exceeds 70% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref FrontendServiceName
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  BackendMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-backend-high-memory
      AlarmDescription: Alert when backend memory exceeds 80% for 5 minutes
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref BackendServiceName
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

Outputs:
  AlertTopicArn:
    Description: SNS Topic ARN for Alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${EnvironmentName}-AlertTopicArn
