name: Upload CloudFormation Templates to S3

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/cloudformation/**'
  workflow_dispatch:

jobs:
  upload-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload CloudFormation templates to S3
        run: |
          aws s3 sync infrastructure/cloudformation/ s3://vistora-cloudformation-templates-781177225477/ \
            --exclude "*" \
            --include "*.yaml" \
            --delete
          echo "✅ CloudFormation templates uploaded successfully"

      - name: List uploaded templates
        run: |
          echo "📋 Uploaded templates:"
          aws s3 ls s3://vistora-cloudformation-templates-781177225477/
